name: binary
description: A binary serializer.
version: 0.0.2+null.safety
homepage: https://github.com/marcelgarus/portals

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  meta: ^1.1.8
  test: ^1.22.0
  zekfad_lints: ^1.1.0
dependencies:
  collection: ^1.17.0
