name: binary
description: A binary serializer.
version: 1.0.0
homepage: https://github.com/marcelgarus/portals

environment:
  sdk: ">=3.3.0-0 <4.0.0"

dev_dependencies:
  meta: ^1.11.0
  test: ^1.24.9
  zekfad_lints: ^1.2.0

dependencies:
  collection: ^1.18.0
